### ISSUE TITLE
Empy biome-grid..where to look next?

### ISSUE THREAD

**Issue by PBorocz** [SqrtMinusOne/biome#2]
Hi Korytov...this is a very cool package, thanks for taking the time to do it (and the work to wrap Open-Meteo like this...I particularly appreciate the use of `transient` for the interface..._weather like magit_! ;-))

- Only nit I ran into on install was that I also needed to use-package on `ct` (in case anyone else runs into it).
- Was able to setup a default location and issue what I think would be a valid query but my `*biome-grid*` buffer is empty after a query *and* there's no `*biome-api-error*` created ...anywhere else to look to see what might be going on? Anything I can flip on in the code to get more diagnostics?? 

Thanks again for the great work!
p

FWIW, here's my [org config](https://github.com/PBorocz/.emacs.d/blob/trunk/config.org#biome-weather)

**Comment by marlinstrub** [comment]
My first query was also blank and it turns out I just hadn't chosen any variables.

For example, when you want a weather forecast for a specific location, you'll have to choose which variables you want to include in the forecast. So after `ww`, press `h` or `d` to select variables, depending on whether you want daily or hourly forecasts.

**Comment by PBorocz** [comment]
Ooooohh...peachy! Works like a champ...thanks @marlinstrub !!

**Comment by SqrtMinusOne** [comment]
Hehe. I'll make it a bit more noticeable I guess, thanks for reporting.
